# Generated by Django 4.2.3 on 2023-07-08 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailMessage', models.EmailField(default='email@email.com', max_length=254, verbose_name='Lead email')),
                ('nameMessage', models.TextField(verbose_name='Lead name')),
                ('messageMessage', models.TextField(verbose_name='Lead message')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='Date of published message')),
            ],
        ),
    ]
